// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "go-metablox/app/foundation/internal/logic/bizcfg"
	_ "go-metablox/app/foundation/internal/logic/bizctx"
	_ "go-metablox/app/foundation/internal/logic/dappcfg"
	_ "go-metablox/app/foundation/internal/logic/faucet"
	_ "go-metablox/app/foundation/internal/logic/heartbeat"
	_ "go-metablox/app/foundation/internal/logic/middleware"
	_ "go-metablox/app/foundation/internal/logic/openroaming"
	_ "go-metablox/app/foundation/internal/logic/verifiable"
)
