// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-metablox/app/foundation/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IBizCtx interface {
		Init(r *ghttp.Request)
		SetUser(ctx context.Context, user *model.CurrentUser)
		CurrentUser(ctx context.Context) *model.CurrentUser
		SetValue(ctx context.Context, key string, value any)
		GetValue(ctx context.Context, key string) any
	}
)

var (
	localBizCtx IBizCtx
)

func BizCtx() IBizCtx {
	if localBizCtx == nil {
		panic("implement not found for interface IBizCtx, forgot register?")
	}
	return localBizCtx
}

func RegisterBizCtx(i IBizCtx) {
	localBizCtx = i
}
