// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"go-metablox/app/foundation/internal/model"
	"math/big"

	"github.com/MetaBloxIO/did-sdk-go/registry"
	"github.com/ethereum/go-ethereum/accounts"
	"github.com/ethereum/go-ethereum/accounts/keystore"
	"github.com/ethereum/go-ethereum/ethclient"
)

type (
	IBizCfg interface {
		WalletStore() *keystore.KeyStore
		Cfg() model.Config
		FaucetWallet() accounts.Account
		RegistryWallet() accounts.Account
		Client() *ethclient.Client
		Registry() *registry.Registry
		ChainID() *big.Int
	}
)

var (
	localBizCfg IBizCfg
)

func BizCfg() IBizCfg {
	if localBizCfg == nil {
		panic("implement not found for interface IBizCfg, forgot register?")
	}
	return localBizCfg
}

func RegisterBizCfg(i IBizCfg) {
	localBizCfg = i
}
