// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-metablox/app/foundation/internal/model"
)

type (
	IFaucet interface {
		Claims(ctx context.Context, in model.FaucetClaimsInput) (out *model.FaucetClaimsOutput, err error)
	}
)

var (
	localFaucet IFaucet
)

func Faucet() IFaucet {
	if localFaucet == nil {
		panic("implement not found for interface IFaucet, forgot register?")
	}
	return localFaucet
}

func RegisterFaucet(i IFaucet) {
	localFaucet = i
}
