// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-metablox/app/foundation/internal/model"
)

type (
	IOpenroaming interface {
		GetUserInfo(ctx context.Context, username string) (*model.WifiUserInfoOutput, error)
		CreateUser(ctx context.Context, in model.CreateWifiUserInfoInput) (int64, error)
	}
)

var (
	localOpenroaming IOpenroaming
)

func Openroaming() IOpenroaming {
	if localOpenroaming == nil {
		panic("implement not found for interface IOpenroaming, forgot register?")
	}
	return localOpenroaming
}

func RegisterOpenroaming(i IOpenroaming) {
	localOpenroaming = i
}
