// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go-metablox/app/foundation/internal/model"

	"github.com/MetaBloxIO/did-sdk-go"
)

type (
	IVerifiable interface {
		Nonce(ctx context.Context, in model.VCNonceInput) (*model.VCChallengeOutput, error)
		VerifyVP(ctx context.Context, in did.VerifiablePresentation) error
		VerifyVC(ctx context.Context, in did.VerifiableCredential) error
		IssueVC(ctx context.Context, in model.IssueVCInput) (*model.IssueVCOutput, error)
		RenewVC(ctx context.Context, in model.VCInput) (*model.VCOutput, error)
		RevokeVC(ctx context.Context, in model.VCInput) error
	}
)

var (
	localVerifiable IVerifiable
)

func Verifiable() IVerifiable {
	if localVerifiable == nil {
		panic("implement not found for interface IVerifiable, forgot register?")
	}
	return localVerifiable
}

func RegisterVerifiable(i IVerifiable) {
	localVerifiable = i
}
