// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DappNodeDao is the data access object for table dapp_node.
type DappNodeDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns DappNodeColumns // columns contains all the column names of Table for convenient usage.
}

// DappNodeColumns defines and stores column names for table dapp_node.
type DappNodeColumns struct {
	Id        string //
	BizType   string //
	ChainId   string //
	RpcUrl    string //
	WssUrl    string //
	Disabled  string //
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
	Remark    string //
}

// dappNodeColumns holds the columns for table dapp_node.
var dappNodeColumns = DappNodeColumns{
	Id:        "id",
	BizType:   "biz_type",
	ChainId:   "chain_id",
	RpcUrl:    "rpc_url",
	WssUrl:    "wss_url",
	Disabled:  "disabled",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	Remark:    "remark",
}

// NewDappNodeDao creates and returns a new DAO object for table data access.
func NewDappNodeDao() *DappNodeDao {
	return &DappNodeDao{
		group:   "default",
		table:   "dapp_node",
		columns: dappNodeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DappNodeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DappNodeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DappNodeDao) Columns() DappNodeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DappNodeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DappNodeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DappNodeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
