// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DappNode is the golang structure for table dapp_node.
type DappNode struct {
	Id        int       `json:"id"        description:""`
	BizType   string    `json:"bizType"   description:""`
	ChainId   int64     `json:"chainId"   description:""`
	RpcUrl    string    `json:"rpcUrl"    description:""`
	WssUrl    string    `json:"wssUrl"    description:""`
	Disabled  int       `json:"disabled"  description:""`
	CreatedAt time.Time `json:"createdAt" description:""`
	UpdatedAt time.Time `json:"updatedAt" description:""`
	DeletedAt time.Time `json:"deletedAt" description:""`
	Remark    string    `json:"remark"    description:""`
}
