// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DappContract is the golang structure for table dapp_contract.
type DappContract struct {
	Id              int       `json:"id"              description:""`
	BizType         string    `json:"bizType"         description:""`
	ContractType    string    `json:"contractType"    description:""`
	Description     string    `json:"description"     description:""`
	ChainId         int64     `json:"chainId"         description:""`
	ContractAddress string    `json:"contractAddress" description:""`
	CreatorAddress  string    `json:"creatorAddress"  description:""`
	TxHash          string    `json:"txHash"          description:""`
	BlockTimestamp  int64     `json:"blockTimestamp"  description:""`
	BlockNumber     int64     `json:"blockNumber"     description:""`
	Disabled        int       `json:"disabled"        description:""`
	Version         string    `json:"version"         description:""`
	Abi             string    `json:"abi"             description:""`
	CreatedAt       time.Time `json:"createdAt"       description:""`
	UpdatedAt       time.Time `json:"updatedAt"       description:""`
	DeletedAt       time.Time `json:"deletedAt"       description:""`
}
