// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DappFaucetRecord is the golang structure for table dapp_faucet_record.
type DappFaucetRecord struct {
	Id          int64     `json:"id"          description:""`
	Account     string    `json:"account"     description:""`
	TxHash      string    `json:"txHash"      description:""`
	TxConfirmed bool      `json:"txConfirmed" description:""`
	Amount      float64   `json:"amount"      description:""`
	DeletedAt   time.Time `json:"deletedAt"   description:"logic delete"`
	CreatedAt   time.Time `json:"createdAt"   description:"when a record was created"`
	UpdatedAt   time.Time `json:"updatedAt"   description:"when a record was updated"`
	Remark      string    `json:"remark"      description:""`
}
