// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DidDocument is the golang structure for table did_document.
type DidDocument struct {
	Id        int64     `json:"id"        description:""`
	ChainId   int64     `json:"chainId"   description:""`
	Did       int64     `json:"did"       description:""`
	RawText   string    `json:"rawText"   description:""`
	CreatedAt time.Time `json:"createdAt" description:""`
	UpdatedAt time.Time `json:"updatedAt" description:""`
	DeletedAt time.Time `json:"deletedAt" description:""`
}
