// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DidVerifiableCredential is the golang structure for table did_verifiable_credential.
type DidVerifiableCredential struct {
	Id                int64     `json:"id"                description:""`
	ChainId           int64     `json:"chainId"           description:""`
	Context           string    `json:"context"           description:""`
	Name              string    `json:"name"              description:""`
	Type              string    `json:"type"              description:""`
	Issuer            string    `json:"issuer"            description:""`
	Holder            string    `json:"holder"            description:""`
	CredentialSubject string    `json:"credentialSubject" description:""`
	IssuanceDate      time.Time `json:"issuanceDate"      description:""`
	ExpirationDate    time.Time `json:"expirationDate"    description:""`
	RevokedAt         time.Time `json:"revokedAt"         description:""`
	Proof             string    `json:"proof"             description:""`
	RawText           string    `json:"rawText"           description:""`
	CreatedAt         time.Time `json:"createdAt"         description:""`
	UpdatedAt         time.Time `json:"updatedAt"         description:""`
	DeletedAt         time.Time `json:"deletedAt"         description:""`
	Description       string    `json:"description"       description:""`
}
