// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// DidWorkloadRecord is the golang structure for table did_workload_record.
type DidWorkloadRecord struct {
	Id           int64     `json:"id"           description:""`
	MinerDid     string    `json:"minerDid"     description:""`
	ValidatorDid string    `json:"validatorDid" description:""`
	Sn           string    `json:"sn"           description:""`
	Model        string    `json:"model"        description:""`
	Tracks       string    `json:"tracks"       description:""`
	Qos          string    `json:"qos"          description:""`
	CreatedAt    time.Time `json:"createdAt"    description:""`
	UpdatedAt    time.Time `json:"updatedAt"    description:""`
	DeletedAt    time.Time `json:"deletedAt"    description:""`
}
