// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// MinerInfo is the golang structure for table miner_info.
type MinerInfo struct {
	Id              int64     `json:"id"              description:"primary key"`
	Name            string    `json:"name"            description:""`
	Did             string    `json:"did"             description:"miner did"`
	Sn              string    `json:"sn"              description:"serial number"`
	Mac             string    `json:"mac"             description:"mac address"`
	BrandName       string    `json:"brandName"       description:"brand name"`
	ModelName       string    `json:"modelName"       description:"Device Model Name"`
	WalletAddress   string    `json:"walletAddress"   description:"miner address"`
	IsVirtual       bool      `json:"isVirtual"       description:"indicates if miner is virtual or not"`
	IsRegistered    bool      `json:"isRegistered"    description:"indicates if miner is registered or not"`
	IsHidden        bool      `json:"isHidden"        description:"visible status"`
	LastHeartbeatAt time.Time `json:"lastHeartbeatAt" description:"the last heartbeat time"`
	FirstBootAt     time.Time `json:"firstBootAt"     description:"the first boot time"`
	Ipv4            string    `json:"ipv4"            description:"ipv4"`
	Ipv6            string    `json:"ipv6"            description:"ipv6"`
	Latitude        float64   `json:"latitude"        description:"latitude of miner location"`
	Longitude       float64   `json:"longitude"       description:"longitude of miner location"`
	DeviceAddress   string    `json:"deviceAddress"   description:"device address"`
	Hostname        string    `json:"hostname"        description:"Device Hostname"`
	System          string    `json:"system"          description:"System type and configuration"`
	Kernel          string    `json:"kernel"          description:"Operating System Kernel version"`
	BoardName       string    `json:"boardName"       description:"Board name"`
	ReleaseInfo     string    `json:"releaseInfo"     description:"release infomation"`
	Disabled        bool      `json:"disabled"        description:""`
	CreatedAt       time.Time `json:"createdAt"       description:"when a record was created"`
	UpdatedAt       time.Time `json:"updatedAt"       description:"when a record was updated"`
	DeletedAt       time.Time `json:"deletedAt"       description:"logic delete"`
	Remark          string    `json:"remark"          description:""`
}
