// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Radcheck is the golang structure for table radcheck.
type Radcheck struct {
	Id        uint   `json:"id"        description:""`
	Username  string `json:"username"  description:""`
	Attribute string `json:"attribute" description:""`
	Op        string `json:"op"        description:""`
	Value     string `json:"value"     description:""`
}
