// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DappNode is the golang structure of table dapp_node for DAO operations like Where/Data.
type DappNode struct {
	g.Meta    `orm:"table:dapp_node, do:true"`
	Id        interface{} //
	BizType   interface{} //
	ChainId   interface{} //
	RpcUrl    interface{} //
	WssUrl    interface{} //
	Disabled  interface{} //
	CreatedAt interface{} //
	UpdatedAt interface{} //
	DeletedAt interface{} //
	Remark    interface{} //
}
