// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DappContract is the golang structure of table dapp_contract for DAO operations like Where/Data.
type DappContract struct {
	g.Meta          `orm:"table:dapp_contract, do:true"`
	Id              interface{} //
	BizType         interface{} //
	ContractType    interface{} //
	Description     interface{} //
	ChainId         interface{} //
	ContractAddress interface{} //
	CreatorAddress  interface{} //
	TxHash          interface{} //
	BlockTimestamp  interface{} //
	BlockNumber     interface{} //
	Disabled        interface{} //
	Version         interface{} //
	Abi             interface{} //
	CreatedAt       interface{} //
	UpdatedAt       interface{} //
	DeletedAt       interface{} //
}
