// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DappFaucetRecord is the golang structure of table dapp_faucet_record for DAO operations like Where/Data.
type DappFaucetRecord struct {
	g.Meta      `orm:"table:dapp_faucet_record, do:true"`
	Id          interface{} //
	Account     interface{} //
	TxHash      interface{} //
	TxConfirmed interface{} //
	Amount      interface{} //
	DeletedAt   interface{} // logic delete
	CreatedAt   interface{} // when a record was created
	UpdatedAt   interface{} // when a record was updated
	Remark      interface{} //
}
