// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DidVerifiableCredential is the golang structure of table did_verifiable_credential for DAO operations like Where/Data.
type DidVerifiableCredential struct {
	g.Meta            `orm:"table:did_verifiable_credential, do:true"`
	Id                interface{} //
	ChainId           interface{} //
	Context           interface{} //
	Name              interface{} //
	Type              interface{} //
	Issuer            interface{} //
	Holder            interface{} //
	CredentialSubject interface{} //
	IssuanceDate      interface{} //
	ExpirationDate    interface{} //
	RevokedAt         interface{} //
	Proof             interface{} //
	RawText           interface{} //
	CreatedAt         interface{} //
	UpdatedAt         interface{} //
	DeletedAt         interface{} //
	Description       interface{} //
}
