// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DidDocument is the golang structure of table did_document for DAO operations like Where/Data.
type DidDocument struct {
	g.Meta    `orm:"table:did_document, do:true"`
	Id        interface{} //
	ChainId   interface{} //
	Did       interface{} //
	RawText   interface{} //
	CreatedAt interface{} //
	UpdatedAt interface{} //
	DeletedAt interface{} //
}
