// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// DidWorkloadRecord is the golang structure of table did_workload_record for DAO operations like Where/Data.
type DidWorkloadRecord struct {
	g.Meta       `orm:"table:did_workload_record, do:true"`
	Id           interface{} //
	MinerDid     interface{} //
	ValidatorDid interface{} //
	Sn           interface{} //
	Model        interface{} //
	Tracks       interface{} //
	Qos          interface{} //
	CreatedAt    interface{} //
	UpdatedAt    interface{} //
	DeletedAt    interface{} //
}
