// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MinerInfo is the golang structure of table miner_info for DAO operations like Where/Data.
type MinerInfo struct {
	g.Meta          `orm:"table:miner_info, do:true"`
	Id              interface{} // primary key
	Name            interface{} //
	Did             interface{} // miner did
	Sn              interface{} // serial number
	Mac             interface{} // mac address
	BrandName       interface{} // brand name
	ModelName       interface{} // Device Model Name
	WalletAddress   interface{} // miner address
	IsVirtual       interface{} // indicates if miner is virtual or not
	IsRegistered    interface{} // indicates if miner is registered or not
	IsHidden        interface{} // visible status
	LastHeartbeatAt interface{} // the last heartbeat time
	FirstBootAt     interface{} // the first boot time
	Ipv4            interface{} // ipv4
	Ipv6            interface{} // ipv6
	Latitude        interface{} // latitude of miner location
	Longitude       interface{} // longitude of miner location
	DeviceAddress   interface{} // device address
	Hostname        interface{} // Device Hostname
	System          interface{} // System type and configuration
	Kernel          interface{} // Operating System Kernel version
	BoardName       interface{} // Board name
	ReleaseInfo     interface{} // release infomation
	Disabled        interface{} //
	CreatedAt       interface{} // when a record was created
	UpdatedAt       interface{} // when a record was updated
	DeletedAt       interface{} // logic delete
	Remark          interface{} //
}
