// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Radcheck is the golang structure of table radcheck for DAO operations like Where/Data.
type Radcheck struct {
	g.Meta    `orm:"table:radcheck, do:true"`
	Id        interface{} //
	Username  interface{} //
	Attribute interface{} //
	Op        interface{} //
	Value     interface{} //
}
