// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-metablox/app/foundation/internal/dao/internal"
)

// internalDappContractDao is internal type for wrapping internal DAO implements.
type internalDappContractDao = *internal.DappContractDao

// dappContractDao is the data access object for table dapp_contract.
// You can define custom methods on it to extend its functionality as you wish.
type dappContractDao struct {
	internalDappContractDao
}

var (
	// DappContract is globally public accessible object for table dapp_contract operations.
	DappContract = dappContractDao{
		internal.NewDappContractDao(),
	}
)

// Fill with you ideas below.
