// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-metablox/app/foundation/internal/dao/internal"
)

// internalDappFaucetRecordDao is internal type for wrapping internal DAO implements.
type internalDappFaucetRecordDao = *internal.DappFaucetRecordDao

// dappFaucetRecordDao is the data access object for table dapp_faucet_record.
// You can define custom methods on it to extend its functionality as you wish.
type dappFaucetRecordDao struct {
	internalDappFaucetRecordDao
}

var (
	// DappFaucetRecord is globally public accessible object for table dapp_faucet_record operations.
	DappFaucetRecord = dappFaucetRecordDao{
		internal.NewDappFaucetRecordDao(),
	}
)

// Fill with you ideas below.
