// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-metablox/app/foundation/internal/dao/internal"
)

// internalDappNodeDao is internal type for wrapping internal DAO implements.
type internalDappNodeDao = *internal.DappNodeDao

// dappNodeDao is the data access object for table dapp_node.
// You can define custom methods on it to extend its functionality as you wish.
type dappNodeDao struct {
	internalDappNodeDao
}

var (
	// DappNode is globally public accessible object for table dapp_node operations.
	DappNode = dappNodeDao{
		internal.NewDappNodeDao(),
	}
)

// Fill with you ideas below.
