// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-metablox/app/foundation/internal/dao/internal"
)

// internalRadcheckDao is internal type for wrapping internal DAO implements.
type internalRadcheckDao = *internal.RadcheckDao

// radcheckDao is the data access object for table radcheck.
// You can define custom methods on it to extend its functionality as you wish.
type radcheckDao struct {
	internalRadcheckDao
}

var (
	// Radcheck is globally public accessible object for table radcheck operations.
	Radcheck = radcheckDao{
		internal.NewRadcheckDao(),
	}
)

// Fill with you ideas below.
